// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function $$default() {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "What is this about?",
                    className: "text-3xl font-semibold"
                  })
            });
}

export {
  $$default as default,
}
/* react/jsx-runtime Not a pure module */
